/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;

/**
 *
 * @author Pramodya Pathirana
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public Dashboard() {
        initComponents();
        setSize(850, 600);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        place_order = new javax.swing.JButton();
        manage_items = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        place_order.setBackground(new java.awt.Color(204, 255, 204));
        place_order.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        place_order.setForeground(new java.awt.Color(102, 102, 102));
        place_order.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodya Pathirana\\Downloads\\order.png")); // NOI18N
        place_order.setText("Place Orders");
        place_order.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                place_orderMouseClicked(evt);
            }
        });
        place_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                place_orderActionPerformed(evt);
            }
        });
        getContentPane().add(place_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 274, -1));

        manage_items.setBackground(new java.awt.Color(204, 255, 204));
        manage_items.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        manage_items.setForeground(new java.awt.Color(102, 102, 102));
        manage_items.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodya Pathirana\\Downloads\\shopping-bag.png")); // NOI18N
        manage_items.setText("Manage Items");
        manage_items.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        manage_items.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                manage_itemsMouseDragged(evt);
            }
        });
        manage_items.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manage_itemsMouseClicked(evt);
            }
        });
        manage_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manage_itemsActionPerformed(evt);
            }
        });
        getContentPane().add(manage_items, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 274, -1));

        jButton3.setBackground(new java.awt.Color(204, 255, 204));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 102));
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodya Pathirana\\Downloads\\customer.png")); // NOI18N
        jButton3.setText("Manage Users");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 274, -1));

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 102, 102));
        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodya Pathirana\\Downloads\\report.png")); // NOI18N
        jButton4.setText("Generate Reports");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 274, -1));

        jButton5.setBackground(new java.awt.Color(204, 255, 204));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 102, 102));
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodya Pathirana\\Downloads\\customer-feedback.png")); // NOI18N
        jButton5.setText("Manage Customers");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setText("Pro Supermarket");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 0, 0));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodya Pathirana\\Downloads\\green-linear-gradient-white-1920x1080-c2-00fa9a-ffffff-a-270-f-14.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1110, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void place_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_place_orderActionPerformed
        
    }//GEN-LAST:event_place_orderActionPerformed

    private void manage_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manage_itemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_itemsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void manage_itemsMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_itemsMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_manage_itemsMouseDragged

    private void manage_itemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manage_itemsMouseClicked
        // TODO add your handling code here:
        Item item = new Item();
        item.setVisible(true);
        
    }//GEN-LAST:event_manage_itemsMouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        CustomerReg customerReg = new CustomerReg();
        customerReg.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Staff staff = new Staff();
        staff.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Report report = new Report();
        report.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4MouseClicked

    private void place_orderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_place_orderMouseClicked
        Order order = new Order();
        order.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_place_orderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manage_items;
    private javax.swing.JButton place_order;
    // End of variables declaration//GEN-END:variables
}
