/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;

import java.sql.*;
import java.util.ArrayList;
import resources.DBConnection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pramodya Pathirana
 */
public class Item extends javax.swing.JFrame {

    /**
     * Creates new form Item
     */
    public Item() {

        initComponents();
        setSize(850, 600);
        setLocationRelativeTo(null);
        getAllItems();
        showTable();
        
    }

    private static Connection connection = DBConnection.getInstance().getConnection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        remove_item = new javax.swing.JButton();
        edit_item = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        clear_item = new javax.swing.JButton();
        item_quantity = new javax.swing.JTextField();
        item_code = new javax.swing.JTextField();
        unit_price = new javax.swing.JTextField();
        item_name = new javax.swing.JTextField();
        add_item = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Manage Items");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        remove_item.setBackground(new java.awt.Color(255, 0, 0));
        remove_item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        remove_item.setForeground(new java.awt.Color(51, 51, 51));
        remove_item.setText("Remove Item");
        remove_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remove_itemActionPerformed(evt);
            }
        });
        getContentPane().add(remove_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        edit_item.setBackground(new java.awt.Color(204, 204, 0));
        edit_item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        edit_item.setForeground(new java.awt.Color(51, 51, 51));
        edit_item.setText("Edit Item");
        edit_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_itemActionPerformed(evt);
            }
        });
        getContentPane().add(edit_item, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 270, 126, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 3));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Item Code :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 85, 30);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Item Name :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 59, 79, 30);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Unit Price :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 99, 79, 30);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Quantity :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 140, 79, 30);

        clear_item.setBackground(new java.awt.Color(255, 0, 0));
        clear_item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clear_item.setForeground(new java.awt.Color(51, 51, 51));
        clear_item.setText("Clear");
        clear_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_itemActionPerformed(evt);
            }
        });
        jPanel1.add(clear_item);
        clear_item.setBounds(360, 90, 140, 29);

        item_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_quantityActionPerformed(evt);
            }
        });
        jPanel1.add(item_quantity);
        item_quantity.setBounds(120, 140, 200, 30);

        item_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_codeActionPerformed(evt);
            }
        });
        jPanel1.add(item_code);
        item_code.setBounds(120, 20, 200, 30);

        unit_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unit_priceActionPerformed(evt);
            }
        });
        jPanel1.add(unit_price);
        unit_price.setBounds(120, 100, 200, 30);

        item_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_nameActionPerformed(evt);
            }
        });
        jPanel1.add(item_name);
        item_name.setBounds(120, 60, 200, 30);

        add_item.setBackground(new java.awt.Color(0, 204, 51));
        add_item.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        add_item.setForeground(new java.awt.Color(51, 51, 51));
        add_item.setText("+ Add new Item");
        add_item.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_itemActionPerformed(evt);
            }
        });
        jPanel1.add(add_item);
        add_item.setBounds(360, 50, 140, 29);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 630, 180));

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(51, 51, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Unit Price", "Quantity", "Added Date", "Added Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 630, 200));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Pramodya Pathirana\\Desktop\\Webp.net-resizeimage.png")); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 120, 130));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void remove_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remove_itemActionPerformed

        try {

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            int selectIndex = jTable2.getSelectedRow();

            String code = model.getValueAt(selectIndex, 0).toString();

            String sql = "DELETE FROM item WHERE item_code=?";
            PreparedStatement pstmt = connection.prepareStatement(sql);

            pstmt.setInt(1, Integer.parseInt(code));
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Deleted");
            showTable();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_remove_itemActionPerformed

    private void edit_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_itemActionPerformed
        try {

            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            int selectIndex = jTable2.getSelectedRow();

            String sql = "UPDATE item SET item_name=?,unit_price=?,item_quantity=? WHERE item_code=?";

            PreparedStatement pstmt = connection.prepareStatement(sql);

            int itemCode = Integer.parseInt(item_code.getText());
            String itemName = item_name.getText();
            double unitPrice = Double.parseDouble(unit_price.getText());
            int qty = Integer.parseInt(item_quantity.getText());
            
            System.out.println(itemName);
            System.out.println(unitPrice);
            System.out.println(qty);
            System.out.println(itemCode);

            pstmt.setString(1, itemName);
            pstmt.setDouble(2, unitPrice);
            pstmt.setInt(3, qty);
            pstmt.setInt(4, itemCode);

            int affectedRows = pstmt.executeUpdate();

            if (affectedRows > 0) {
                JOptionPane.showMessageDialog(null, "Successfully Updated");
                showTable();
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }

    }//GEN-LAST:event_edit_itemActionPerformed

    private void item_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_quantityActionPerformed

    private void clear_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_itemActionPerformed
        item_code.setText(null);
        item_name.setText(null);
        item_quantity.setText(null);
        unit_price.setText(null);
    }//GEN-LAST:event_clear_itemActionPerformed

    public static ArrayList getAllItems() {

        ArrayList itemsList = new ArrayList();
        try {
            String sql = "SELECT * FROM item";
            Statement stmt = connection.createStatement();

            ResultSet res_st = stmt.executeQuery(sql);
            while (res_st.next()) {
                ItemModel singleItem = new ItemModel(
                        res_st.getInt(1),
                        res_st.getString(2),
                        res_st.getDouble(3),
                        res_st.getInt(4),
                        res_st.getDate(5),
                        res_st.getTime(6));
                itemsList.add(singleItem);
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }
        return itemsList;
    }

    public void showTable() {
        ArrayList<ItemModel> showlist = getAllItems();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setNumRows(0);
        Object[] row = new Object[6];
        for (int i = 0; i < showlist.size(); i++) {
            row[0] = showlist.get(i).getItemCode();
            row[1] = showlist.get(i).getItemName();
            row[2] = showlist.get(i).getUnitPrice();
            row[3] = showlist.get(i).getItemQuantity();
            row[4] = showlist.get(i).getAddedDate();
            row[5] = showlist.get(i).getAddedTime();
            System.out.println(row);
            model.addRow(row);
        }
    }


    private void item_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_codeActionPerformed


    private void unit_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unit_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unit_priceActionPerformed

    private void item_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_nameActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        int selectIndex = jTable2.getSelectedRow();

        String code = model.getValueAt(selectIndex, 0).toString();
        String name = model.getValueAt(selectIndex, 1).toString();
        String price = model.getValueAt(selectIndex, 2).toString();
        String quantity = model.getValueAt(selectIndex, 3).toString();

        item_code.setText(code);
        item_name.setText(name);
        unit_price.setText(price);
        item_quantity.setText(code);

    }//GEN-LAST:event_jTable2MouseClicked

    private void add_itemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_itemActionPerformed
        try {
            int id = Integer.parseInt(item_code.getText());
            String name = item_name.getText();
            double price = Double.parseDouble(unit_price.getText());
            int quantity = Integer.parseInt(item_quantity.getText());

            String sql = "INSERT INTO item(item_code,item_name,unit_price,item_quantity)" + "VALUES (?,?,?,?)";

            PreparedStatement pstmt = connection.prepareStatement(sql);

            pstmt.setObject(1, id);
            pstmt.setObject(2, name);
            pstmt.setObject(3, price);
            pstmt.setObject(4, quantity);

            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successfully Inserted");
            showTable();
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
    }//GEN-LAST:event_add_itemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Item.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Item().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_item;
    private javax.swing.JButton clear_item;
    private javax.swing.JButton edit_item;
    private javax.swing.JTextField item_code;
    private javax.swing.JTextField item_name;
    private javax.swing.JTextField item_quantity;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JButton remove_item;
    private javax.swing.JTextField unit_price;
    // End of variables declaration//GEN-END:variables
}

class ItemModel {

    int item_code;
    String item_name;
    double unit_price;
    int item_quantity;
    Date added_date;
    Time added_time;

    ItemModel(int a, String b, double c, int d, Date e, Time f) {
        this.item_code = a;
        this.item_name = b;
        this.unit_price = c;
        this.item_quantity = d;
        this.added_date = e;
        this.added_time = f;
    }

    public int getItemCode() {
        return item_code;
    }

    public String getItemName() {
        return item_name;
    }

    public double getUnitPrice() {
        return unit_price;
    }

    public int getItemQuantity() {
        return item_quantity;
    }

    public Date getAddedDate() {
        return added_date;
    }

    public Time getAddedTime() {
        return added_time;
    }

    Object getCustomer_id() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

}
