package inventorymanagement;


import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import resources.DBConnection;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Sashini Shihara
 */
public class Order extends javax.swing.JFrame {

    /**
     * Creates new form order1
     */
    public Order() {
        initComponents();
        setSize(850, 600);
        setLocationRelativeTo(null);
    }
    private static Connection connection = DBConnection.getInstance().getConnection();
    ArrayList<items> order = new ArrayList();
    double tot = 0.0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_cname = new javax.swing.JTextField();
        txt_hQty = new javax.swing.JTextField();
        txt_iname = new javax.swing.JTextField();
        txt_tot = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_uprice = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_chk = new javax.swing.JButton();
        txt_icode = new javax.swing.JTextField();
        txt_cid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 174, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setText("Total :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 72, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Qty on Hand");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 174, -1));

        txt_cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cnameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 172, 37));
        jPanel1.add(txt_hQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 110, 30));
        jPanel1.add(txt_iname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, 30));
        jPanel1.add(txt_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, 172, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Place New Order");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 356, 60));
        jPanel1.add(txt_uprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel2.setText("Customer Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 174, -1));
        jPanel1.add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 100, 30));

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Item Name", "Qty", "Unit Price", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 730, 180));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Item Code ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 174, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Item Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 174, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setText("Customer ID :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 174, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Unit price");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 174, -1));

        btn_add.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btn_add.setText("Add");
        btn_add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 80, 30));

        btn_chk.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        btn_chk.setText("Checkout");
        btn_chk.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_chk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chkActionPerformed(evt);
            }
        });
        jPanel1.add(btn_chk, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 170, 30));

        txt_icode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_icodeFocusLost(evt);
            }
        });
        txt_icode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_icodeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_icode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 100, 30));

        txt_cid.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cidFocusLost(evt);
            }
        });
        txt_cid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cidActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cid, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 172, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chkActionPerformed
        try {
//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "");

            String sql1 = "INSERT INTO order_details(item_code,item_quantity,amount)" + " VALUES (?,?,?)";

            PreparedStatement pstm = connection.prepareStatement(sql1);

            for (int i = 0; i < order.size(); i++) {
                pstm.setObject(1, order.get(i).getIcode());
                pstm.setObject(2, order.get(i).getQty());
                pstm.setObject(3, order.get(i).getAmt());

                pstm.executeUpdate();
            }

//            con.close();
        } catch (SQLException ex) {
            System.out.println(ex);
        }

//        Date date = (Date) txt_odate.getDate();
        String cid = (String) txt_cid.getText();
        try {

//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "");
            String sql = "INSERT INTO sales_order(order_total,customer_id)" + " VALUES (?,?)";

            PreparedStatement pstm = connection.prepareStatement(sql);

            pstm.setObject(1, tot);
//            pstm.setObject(2, date);

            pstm.setObject(2, Integer.parseInt(cid));

            pstm.executeUpdate();
//            con.close();

        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btn_chkActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        String icode = txt_icode.getText();
        int qty = parseInt(txt_qty.getText());
        double uprice = parseDouble(txt_uprice.getText());
        int hqty = parseInt(txt_hQty.getText());
        String name = txt_iname.getText();

        double amt = (double) uprice * qty;

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        order.add(new items(icode, qty, amt));
        model.addRow(new Object[]{icode, name, qty, uprice, amt});

        double a = 0.0;
        for (int i = 0; i < jTable1.getRowCount(); i++) {

            a = (double) jTable1.getValueAt(i, 4);

        }

        tot = tot + a;

        String tot1;
        tot1 = Double.toString(tot);
        txt_tot.setText(tot1);
        String cid = txt_cid.getText();
        String cname = txt_cname.getText();
//        String oid = txt_oID.getText();



    }//GEN-LAST:event_btn_addActionPerformed

    private void txt_cidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cidActionPerformed

    private void txt_cidFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cidFocusLost

        try {

//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "");
            String cid = txt_cid.getText();

            String sql = "select customer_name from customer where customer_id='" + cid + "'";

            PreparedStatement pstm = connection.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery(sql);

            while (rs.next()) {
                String name = rs.getString("customer_name");
                txt_cname.setText(name);
            }

        } catch (SQLException ex) {
            System.out.println(ex);
        }


    }//GEN-LAST:event_txt_cidFocusLost

    private void txt_cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cnameActionPerformed

    private void txt_icodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_icodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_icodeActionPerformed

    private void txt_icodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_icodeFocusLost
 try {

//            Class.forName("com.mysql.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "");

            String iid = txt_icode.getText();
            
            String sql = "select item_name,unit_price,item_quantity from item where item_code='"+iid+"'";
            
            PreparedStatement pstm = connection.prepareStatement(sql);
            ResultSet rs = pstm.executeQuery(sql);
            
            while(rs.next())
            {
            String name=rs.getString("item_name");
            txt_iname.setText(name);
            
            String qt=rs.getString("item_quantity");
            txt_hQty.setText(qt);
            
            String pr=rs.getString("unit_price");
            txt_uprice.setText(pr);
            }

            
            

        } catch (SQLException ex) {
            System.out.println(ex);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txt_icodeFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Order.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Order().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_chk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_cid;
    private javax.swing.JTextField txt_cname;
    private javax.swing.JTextField txt_hQty;
    private javax.swing.JTextField txt_icode;
    private javax.swing.JTextField txt_iname;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_tot;
    private javax.swing.JTextField txt_uprice;
    // End of variables declaration//GEN-END:variables
}
