/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagement;


import inventorymanagement.AddingStaff;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aamir ali Shafeek
 */
public class Staff extends javax.swing.JFrame {
    //Connection con=null;
    String ArrayList[];

    /**
     * Creates new form Staff
     */
    public Staff() {
        initComponents();
        setSize(850, 600);
        setLocationRelativeTo(null);
        showTable();

    }
    public static ArrayList getAllItems() {

        ArrayList staffList = new ArrayList();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            String sql = "SELECT * FROM staff";
            Statement stmt = con.createStatement();  

            ResultSet res_st = stmt.executeQuery(sql);
            
            staffModel staffmodel;
            while (res_st.next()) {
                staffmodel = new staffModel(res_st.getInt("staff_id"),res_st.getString("staff_name"),res_st.getString("staff_address"),res_st.getInt("staff_tel"),res_st.getString("priviledge"));
                 staffList.add(staffmodel);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        return staffList;
    }

    public void showTable() {
        ArrayList<staffModel> showlist = getAllItems();
        DefaultTableModel model = (DefaultTableModel) Table_Staff.getModel();
        Object[] row = new Object[5];
        model.setNumRows(0);
        for (int i = 0; i < showlist.size(); i++) {
            row[0] = showlist.get(i).getsno();
            row[1] = showlist.get(i).getname();
            row[2] = showlist.get(i).getaddress();
            row[3] = showlist.get(i).gettelNo();
            row[4] = showlist.get(i).getprivilege();
            System.out.println(row);
            model.addRow(row);
        }
    }

    private void Update_table() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        newStaff = new javax.swing.JButton();
        deleteStaff = new javax.swing.JButton();
        search_staff = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Staff = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        staffId = new javax.swing.JTextField();
        staffName = new javax.swing.JTextField();
        telNo = new javax.swing.JTextField();
        privilege = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(102, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressActionPerformed(evt);
            }
        });
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 250, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Address:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("Menu");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 700, 90, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Go to Home Page...");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 710, -1, -1));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 140, -1));

        update.setBackground(new java.awt.Color(102, 102, 255));
        update.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 120, 38));

        newStaff.setBackground(new java.awt.Color(102, 102, 255));
        newStaff.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        newStaff.setText("Add New Staff");
        newStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStaffActionPerformed(evt);
            }
        });
        getContentPane().add(newStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, 40));

        deleteStaff.setBackground(new java.awt.Color(102, 102, 255));
        deleteStaff.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        deleteStaff.setText("Delete Staff");
        deleteStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStaffActionPerformed(evt);
            }
        });
        getContentPane().add(deleteStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 180, 150, 40));

        search_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_staffActionPerformed(evt);
            }
        });
        getContentPane().add(search_staff, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 189, 37));

        search.setBackground(new java.awt.Color(102, 102, 255));
        search.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 90, 110, 34));

        Table_Staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Staff Name", "Address", "Telephone Number", "Privilege"
            }
        ));
        jScrollPane1.setViewportView(Table_Staff);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 860, 421));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Staff Details");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 24, 238, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Staff Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Staff ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("TelePhone No.");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Privilage");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        staffId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffIdActionPerformed(evt);
            }
        });
        getContentPane().add(staffId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 100, 30));

        staffName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffNameActionPerformed(evt);
            }
        });
        getContentPane().add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, 30));
        getContentPane().add(telNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 140, 30));

        privilege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                privilegeActionPerformed(evt);
            }
        });
        getContentPane().add(privilege, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStaffActionPerformed
        // TODO add your handling code here:

        AddingStaff s = new AddingStaff();
        s.setVisible(true);
    }//GEN-LAST:event_newStaffActionPerformed

    private void search_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_staffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_search_staffActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String searchId = search_staff.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory", "root", "");
            String sql = "SELECT staff_id, staff_name, staff_address,staff_tel, priviledge FROM staff WHERE staff_id ='" + searchId + "' ";

            Statement pstmt = con.createStatement();

            ResultSet rs = pstmt.executeQuery(sql);

            if (rs.next()) {
                staffId.setText(rs.getString("staff_id"));
                staffName.setText(rs.getString("staff_name"));
                address.setText(rs.getString("staff_address"));
                telNo.setText(rs.getString("staff_tel"));
                privilege.setText(rs.getString("priviledge"));

            } else {
                JOptionPane.showMessageDialog(null, "Record not Found");
            }
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "hello" + e);
        }


    }//GEN-LAST:event_searchActionPerformed

    private void staffNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffNameActionPerformed

    private void privilegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_privilegeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_privilegeActionPerformed

    private void staffIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffIdActionPerformed

    private void deleteStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStaffActionPerformed
        // TODO add your handling code here:
        String staffId=search_staff.getText();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            String sql = "delete from staff where staff_id='" + staffId + "' ";
            PreparedStatement pstm = con.prepareStatement(sql);
            
            
         pstm.executeUpdate();
         JOptionPane.showMessageDialog(null,"Successfully Deleted!");
         con.close();
        } catch (Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        showTable();
    }//GEN-LAST:event_deleteStaffActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String searchId = search_staff.getText();
        try{
           Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
           
           String sql = "UPDATE staff SET staff_id =?,staff_name =?,staff_address = ?,staff_tel =?,priviledge =? WHERE staff_id ='" + searchId + "' ";
           PreparedStatement pstmt = con.prepareStatement(sql);
           
           pstmt.setInt(1,Integer.parseInt(staffId.getText()));
           pstmt.setString(2,staffName.getText());
           pstmt.setString(3,address.getText());
           pstmt.setInt(4,Integer.parseInt(telNo.getText()));
           pstmt.setString(5,privilege.getText());
          
           
           
           pstmt.executeUpdate();
           JOptionPane.showMessageDialog(null,"Successfully Updated");
           con.close();
       
       }catch(Exception e)
       {
           JOptionPane.showMessageDialog(null,e);
       }
       showTable();

    }//GEN-LAST:event_updateActionPerformed

    private void addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        staffId.setText("");
        staffName.setText("");
        telNo.setText("");
        address.setText("");
        privilege.setText("");
        search_staff.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Staff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Staff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_Staff;
    private javax.swing.JTextField address;
    private javax.swing.JButton deleteStaff;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newStaff;
    private javax.swing.JTextField privilege;
    private javax.swing.JButton search;
    private javax.swing.JTextField search_staff;
    private javax.swing.JTextField staffId;
    private javax.swing.JTextField staffName;
    private javax.swing.JTextField telNo;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void showTableData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
